# Generated by Django 5.1.1 on 2024-10-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_alter_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('moderator', 'Moderator'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], max_length=50),
        ),
    ]
