# Generated by Django 5.1.1 on 2024-10-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apellido',
            field=models.CharField(max_length=30, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('moderator', 'Moderator'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], default='User', max_length=20, verbose_name='Rol'),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
