# Generated by Django 5.1.1 on 2024-10-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customuser_apellido_remove_customuser_cedula_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(max_length=30, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission'),
        ),
    ]
